---
title: "Portfolio"
author: "Vivek Sinha"
date: "29/02/2020"
output: 
  prettydoc::html_pretty:
    theme: tactile
---

## Experience

My role as a Corporate Trainer included working mainly with Microsoft SQL Server database. Being proficient in this technology, I utilize my expertize to train professionals within the organization on the following concepts:

* L1 Level Activities

  + Installation of MS SQL Server 2012/2016 databases
  + User creation amd management
  + Server roles and database roles
  + Partitions
  + Indexes
  + Database mail configuration

* L2 Level Activities

  + Server audits and database audits
  + Policy-based management
  + Backup and Recovery
  + Maintenance Plans
  + Contained databases
  + Encryptions
  + Resource Manager
  + Database Profiler and Tuning Advisor

* L3 Level Activities - High Availability Features

  + Database Mirroring
  + Log Shipping
  + Replication
  + AlwaysOn Availability Group
  + Distributed Availability Group

My profile also included setting up and maintaining database environments (playgrounds) for participants to gain hands-on experience working on the technology. I have also collaborated with my team to create video courses to help participants gain the necessary skillset. Every course based on the above topics concluded with a 60-minute multiple-choice based assessment, and one hands-on assessment. Automating the evaluation of these hands-on assessments is one of my achievements I pride upon.

Such in-depth knowledge in this field allowed me to be certified as a [Microsoft Certified Professional](<https://drive.google.com/file/d/1T-DniBL0LyFaBkMx0UzJiK10HuYoFlu8/view?usp=sharing>).

## Masters in Business Analytics and Big Data

1. MAchine Learning

    + Compared machine learning Classification models such as Logistic Regression, Decision Trees and Random Forests (in python) to determine which model accurately predicts whether [breast cancer](<https://viveksinha-git.github.io/DataViz/Breast_Cancer_Detect.html>) caused is benign or malignant
    
    + Developed a [Linear Model](<https://viveksinha-git.github.io/DataViz/Linear-Model-in-R.html>) in R which determines the correlation between air pollutants in Madrid with respect to temperature, humidity, precipitate and win speeds 

2. Hadoop Framework

    + Performed data [ingestion](<https://drive.google.com/file/d/1vhJlGSuqP0tdwQS8AiU44itLp8s6g9p1/view?usp=sharing>) into Hive database to extract knowledgeable insights

3. Recommendation Systems

    + Created a basic [model](<https://viveksinha-git.github.io/DataViz/RS>) to recommend movies to a user

4. Working with PySpark

    + Performed basic operations in [PySpark](<https://viveksinha-git.github.io/DataViz/PySpark_Basic_Operations.html>) to obtain useful insights from `Toronto BikeShare` dataset
    
5. Data Visualization

    + Created a data vizualization [model](<https://viveksinha-git.github.io/DataViz/GoT-Final.html>) to gain useful insights

